### ISSUE TITLE
Rename to 'verifyJwtToken`

### ISSUE THREAD

**Issue by dkryvi** [AlexeyKorkoza/credit-site-server#100]
https://github.com/AlexeyKorkoza/credit-site/blob/7964e82507306d4aec861eeddbcaaee6833c6270/src/middlewares/jwt.js#L4

**Comment by AlexeyKorkoza** [comment]
@dkryvi , please, check the PR #105

**Comment by AlexeyKorkoza** [comment]
It is merged, #105
